// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsKpPuLkcdUfIo0il-0OoZphObdAA0fLw',
    appId: '1:781298465124:android:2ce490dfcff2b84c3c6271',
    messagingSenderId: '781298465124',
    projectId: 'hochzeitds-747ec',
    databaseURL:
        'https://hochzeitds-747ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hochzeitds-747ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-hHMAmE_ZL7pfiScYkRZIiTgAGI70Wvw',
    appId: '1:781298465124:ios:1687dd25472b30193c6271',
    messagingSenderId: '781298465124',
    projectId: 'hochzeitds-747ec',
    databaseURL:
        'https://hochzeitds-747ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hochzeitds-747ec.appspot.com',
    iosBundleId: 'com.example.hochzeitDs',
  );
}
